---
version: 0.6.9
slug: open3e
name: Open3e
description: Connect to E3 Controls through CAN with Open3e Web UI
url: https://github.com/zcerar5/ha-addons/tree/main/open3e
arch:
  - amd64
  - aarch64
hassio_api: true
host_network: true
init: false
ports:
  5051/tcp: 5051
ports_description:
  5051/tcp: Open3e Web UI
webui: http://[HOST]:[PORT:5051]
watchdog: http://[HOST]:[PORT:5051]/api/live-status
options:
  configurations:
    can: can0
    Web_UI_Enabled: false
    Web_UI_Port: 5051
    Listen_Topic: open3e/cmnd
    Server_Topic: open3e
    MQTT_FormatString: "{device}_{ecuAddr:03X}_{didNumber}_{didName}"
    MQTT_ClientID: open3e
    MQTT_Publish_JSON: false
    Auto_Select_HACS_Datapoints: true
    Auto_Select_Room_Datapoints: true
privileged:
  - NET_ADMIN
schema:
  configurations:
    can: str
    Web_UI_Enabled: bool
    Web_UI_Port: port
    Listen_Topic: str
    Server_Topic: str
    MQTT_FormatString: str
    MQTT_ClientID: str
    MQTT_Publish_JSON: bool
    Auto_Select_HACS_Datapoints: bool
    Auto_Select_Room_Datapoints: bool
services:
  - mqtt:need
startup: services
