# This is a basic workflow to help you get started with Actions

# Name of the workflow
name: Build HA Addon

# Triggers the workflow on a published release or manual dispatch
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true

# Migration to new Home Assistant Actions build process

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: ha-addon-open3e
  REGISTRY_PREFIX: ghcr.io/zcerar5

permissions:
  contents: read

# Defines the steps that will run in this workflow
jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6

      - name: Resolve tag
        id: tag
        run: |
          TAG="${{ inputs.tag || github.event.release.tag_name }}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}
          registry-prefix: ${{ env.REGISTRY_PREFIX }}


  build:
    name: Build ${{ matrix.arch }} image
    needs: init
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6

      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          context: "./open3e"
          image: ${{ matrix.image }}
          image-tags: |
            ${{ needs.init.outputs.tag }}
            latest
          labels: |
            io.hass.type=app
            io.hass.name=Open3e
            io.hass.description=Connect to E3 Controls through CAN
            io.hass.url=https://github.com/zcerar5/ha-addons/tree/main/open3e
          push: "true"
          version: ${{ needs.init.outputs.tag }}

  manifest:
    name: Publish multi-arch manifest
    needs: [init, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          registry-prefix: ${{ env.REGISTRY_PREFIX }}
          image-tags: |
            ${{ needs.init.outputs.tag }}
            latest
